Thu,23 Dec 2021 18:18:22 log.py[line:23] DEBUG debug
Thu,23 Dec 2021 18:18:22 log.py[line:24] INFO info
Thu,23 Dec 2021 18:18:22 log.py[line:25] WARNING warning
Thu,23 Dec 2021 18:18:22 log.py[line:26] ERROR error
Thu,23 Dec 2021 18:18:22 log.py[line:27] CRITICAL critical
Thu,23 Dec 2021 18:23:41 log.py[line:23] DEBUG debug
Thu,23 Dec 2021 18:23:41 log.py[line:24] INFO info
Thu,23 Dec 2021 18:23:41 log.py[line:25] WARNING warning
Thu,23 Dec 2021 18:23:41 log.py[line:26] ERROR error
Thu,23 Dec 2021 18:23:41 log.py[line:27] CRITICAL critical
Thu,23 Dec 2021 18:23:41 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Thu,23 Dec 2021 18:23:41 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/flashes/simple?limit=5.0&flag=down&category=0 HTTP/1.1" 422 None
Thu,23 Dec 2021 18:23:41 TestRequest.py[line:83] ERROR testhome2-5
Thu,23 Dec 2021 18:23:41 TestRequest.py[line:84] ERROR 失败
Thu,23 Dec 2021 18:23:41 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The limit field must contain an integer.'}
Thu,23 Dec 2021 18:23:41 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Thu,23 Dec 2021 18:23:41 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/flashes/simple?limit=&flag=down&category=0 HTTP/1.1" 422 None
Thu,23 Dec 2021 18:23:41 TestRequest.py[line:83] ERROR testhome2-5
Thu,23 Dec 2021 18:23:41 TestRequest.py[line:84] ERROR 失败
Thu,23 Dec 2021 18:23:41 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The limit field is required.'}
Fri,24 Dec 2021 15:24:36 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 15:24:36 log.py[line:24] INFO info
Fri,24 Dec 2021 15:24:36 log.py[line:25] WARNING warning
Fri,24 Dec 2021 15:24:36 log.py[line:26] ERROR error
Fri,24 Dec 2021 15:24:36 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 15:24:45 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 15:24:45 log.py[line:24] INFO info
Fri,24 Dec 2021 15:24:45 log.py[line:25] WARNING warning
Fri,24 Dec 2021 15:24:45 log.py[line:26] ERROR error
Fri,24 Dec 2021 15:24:45 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 15:24:45 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:24:50 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=up&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:24:50 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:24:50 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=&flag=down&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:24:50 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:24:50 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=down&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:24:50 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:25:18 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 15:25:18 log.py[line:24] INFO info
Fri,24 Dec 2021 15:25:18 log.py[line:25] WARNING warning
Fri,24 Dec 2021 15:25:18 log.py[line:26] ERROR error
Fri,24 Dec 2021 15:25:18 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 15:25:18 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:25:19 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=up&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:25:19 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:25:19 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=&flag=down&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:25:19 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:25:19 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=down&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:25:19 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:51:04 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 15:51:04 log.py[line:24] INFO info
Fri,24 Dec 2021 15:51:04 log.py[line:25] WARNING warning
Fri,24 Dec 2021 15:51:04 log.py[line:26] ERROR error
Fri,24 Dec 2021 15:51:04 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 15:51:04 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:51:04 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=up&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:51:04 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:51:04 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=&flag=down&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:51:04 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:51:04 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=down&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:51:04 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:53:56 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 15:53:56 log.py[line:24] INFO info
Fri,24 Dec 2021 15:53:56 log.py[line:25] WARNING warning
Fri,24 Dec 2021 15:53:56 log.py[line:26] ERROR error
Fri,24 Dec 2021 15:53:56 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 15:53:56 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:53:57 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=up&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:53:57 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:53:57 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=&flag=down&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:53:57 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:53:57 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=down&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:53:57 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:58:57 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 15:58:57 log.py[line:24] INFO info
Fri,24 Dec 2021 15:58:57 log.py[line:25] WARNING warning
Fri,24 Dec 2021 15:58:57 log.py[line:26] ERROR error
Fri,24 Dec 2021 15:58:57 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 15:58:57 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:58:57 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=up&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:58:57 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:58:57 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=&flag=down&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 15:58:57 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 15:58:57 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=down&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 15:58:57 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 16:03:24 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 16:03:24 log.py[line:24] INFO info
Fri,24 Dec 2021 16:03:24 log.py[line:25] WARNING warning
Fri,24 Dec 2021 16:03:24 log.py[line:26] ERROR error
Fri,24 Dec 2021 16:03:24 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 16:03:24 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 16:03:24 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=up&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 16:03:24 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 16:03:24 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=&flag=down&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 16:03:24 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 16:03:24 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=down&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 16:03:24 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 16:50:59 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 16:50:59 log.py[line:24] INFO info
Fri,24 Dec 2021 16:50:59 log.py[line:25] WARNING warning
Fri,24 Dec 2021 16:50:59 log.py[line:26] ERROR error
Fri,24 Dec 2021 16:50:59 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 16:51:56 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 16:51:56 log.py[line:24] INFO info
Fri,24 Dec 2021 16:51:56 log.py[line:25] WARNING warning
Fri,24 Dec 2021 16:51:56 log.py[line:26] ERROR error
Fri,24 Dec 2021 16:51:56 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 16:52:04 log.py[line:23] DEBUG debug
Fri,24 Dec 2021 16:52:04 log.py[line:24] INFO info
Fri,24 Dec 2021 16:52:04 log.py[line:25] WARNING warning
Fri,24 Dec 2021 16:52:04 log.py[line:26] ERROR error
Fri,24 Dec 2021 16:52:04 log.py[line:27] CRITICAL critical
Fri,24 Dec 2021 16:52:04 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 16:52:05 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=up&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 16:52:05 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 16:52:05 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=&flag=down&information_id=0.0&catelogue_key=industry HTTP/1.1" 422 None
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Fri,24 Dec 2021 16:52:05 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Fri,24 Dec 2021 16:52:05 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "GET /newapi/noah/v1/timelines/other?limit=5.0&flag=down&information_id=0.0&catelogue_key= HTTP/1.1" 422 None
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:83] ERROR testhome2-5
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:84] ERROR 失败
Fri,24 Dec 2021 16:52:05 TestRequest.py[line:85] ERROR 实际返回结果：{'status_code': 422, 'message': 'The information id field must contain an integer.'}
Mon,27 Dec 2021 16:33:24 log.py[line:23] DEBUG debug
Mon,27 Dec 2021 16:33:24 log.py[line:24] INFO info
Mon,27 Dec 2021 16:33:24 log.py[line:25] WARNING warning
Mon,27 Dec 2021 16:33:24 log.py[line:26] ERROR error
Mon,27 Dec 2021 16:33:24 log.py[line:27] CRITICAL critical
Mon,27 Dec 2021 16:40:01 log.py[line:23] DEBUG debug
Mon,27 Dec 2021 16:40:01 log.py[line:24] INFO info
Mon,27 Dec 2021 16:40:01 log.py[line:25] WARNING warning
Mon,27 Dec 2021 16:40:01 log.py[line:26] ERROR error
Mon,27 Dec 2021 16:40:01 log.py[line:27] CRITICAL critical
Mon,27 Dec 2021 16:47:04 log.py[line:23] DEBUG debug
Mon,27 Dec 2021 16:47:04 log.py[line:24] INFO info
Mon,27 Dec 2021 16:47:04 log.py[line:25] WARNING warning
Mon,27 Dec 2021 16:47:04 log.py[line:26] ERROR error
Mon,27 Dec 2021 16:47:04 log.py[line:27] CRITICAL critical
Mon,27 Dec 2021 16:47:12 log.py[line:23] DEBUG debug
Mon,27 Dec 2021 16:47:12 log.py[line:24] INFO info
Mon,27 Dec 2021 16:47:12 log.py[line:25] WARNING warning
Mon,27 Dec 2021 16:47:12 log.py[line:26] ERROR error
Mon,27 Dec 2021 16:47:12 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 10:55:54 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 10:55:54 log.py[line:24] INFO info
Tue,28 Dec 2021 10:55:55 log.py[line:25] WARNING warning
Tue,28 Dec 2021 10:55:55 log.py[line:26] ERROR error
Tue,28 Dec 2021 10:55:55 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 11:01:05 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 11:01:05 log.py[line:24] INFO info
Tue,28 Dec 2021 11:01:05 log.py[line:25] WARNING warning
Tue,28 Dec 2021 11:01:05 log.py[line:26] ERROR error
Tue,28 Dec 2021 11:01:05 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 11:01:05 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): 127.0.0.1:8000
Tue,28 Dec 2021 11:01:48 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 11:01:48 log.py[line:24] INFO info
Tue,28 Dec 2021 11:01:48 log.py[line:25] WARNING warning
Tue,28 Dec 2021 11:01:48 log.py[line:26] ERROR error
Tue,28 Dec 2021 11:01:48 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 11:02:24 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 11:02:24 log.py[line:24] INFO info
Tue,28 Dec 2021 11:02:24 log.py[line:25] WARNING warning
Tue,28 Dec 2021 11:02:24 log.py[line:26] ERROR error
Tue,28 Dec 2021 11:02:24 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 15:21:00 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 15:21:00 log.py[line:24] INFO info
Tue,28 Dec 2021 15:21:00 log.py[line:25] WARNING warning
Tue,28 Dec 2021 15:21:00 log.py[line:26] ERROR error
Tue,28 Dec 2021 15:21:00 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 15:22:16 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 15:22:16 log.py[line:24] INFO info
Tue,28 Dec 2021 15:22:16 log.py[line:25] WARNING warning
Tue,28 Dec 2021 15:22:16 log.py[line:26] ERROR error
Tue,28 Dec 2021 15:22:16 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 15:23:46 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 15:23:46 log.py[line:24] INFO info
Tue,28 Dec 2021 15:23:46 log.py[line:25] WARNING warning
Tue,28 Dec 2021 15:23:46 log.py[line:26] ERROR error
Tue,28 Dec 2021 15:23:46 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 15:26:06 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 15:26:06 log.py[line:24] INFO info
Tue,28 Dec 2021 15:26:06 log.py[line:25] WARNING warning
Tue,28 Dec 2021 15:26:06 log.py[line:26] ERROR error
Tue,28 Dec 2021 15:26:06 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 15:43:15 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 15:43:15 log.py[line:24] INFO info
Tue,28 Dec 2021 15:43:15 log.py[line:25] WARNING warning
Tue,28 Dec 2021 15:43:15 log.py[line:26] ERROR error
Tue,28 Dec 2021 15:43:15 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 16:14:23 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 16:14:23 log.py[line:24] INFO info
Tue,28 Dec 2021 16:14:23 log.py[line:25] WARNING warning
Tue,28 Dec 2021 16:14:23 log.py[line:26] ERROR error
Tue,28 Dec 2021 16:14:23 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 16:16:35 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 16:16:35 log.py[line:24] INFO info
Tue,28 Dec 2021 16:16:35 log.py[line:25] WARNING warning
Tue,28 Dec 2021 16:16:35 log.py[line:26] ERROR error
Tue,28 Dec 2021 16:16:35 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 17:07:25 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 17:07:25 log.py[line:24] INFO info
Tue,28 Dec 2021 17:07:25 log.py[line:25] WARNING warning
Tue,28 Dec 2021 17:07:25 log.py[line:26] ERROR error
Tue,28 Dec 2021 17:07:25 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 17:18:55 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 17:18:55 log.py[line:24] INFO info
Tue,28 Dec 2021 17:18:55 log.py[line:25] WARNING warning
Tue,28 Dec 2021 17:18:55 log.py[line:26] ERROR error
Tue,28 Dec 2021 17:18:55 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 17:19:38 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 17:19:38 log.py[line:24] INFO info
Tue,28 Dec 2021 17:19:38 log.py[line:25] WARNING warning
Tue,28 Dec 2021 17:19:38 log.py[line:26] ERROR error
Tue,28 Dec 2021 17:19:38 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 17:19:49 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 17:19:49 log.py[line:24] INFO info
Tue,28 Dec 2021 17:19:49 log.py[line:25] WARNING warning
Tue,28 Dec 2021 17:19:49 log.py[line:26] ERROR error
Tue,28 Dec 2021 17:19:49 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 17:21:13 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 17:21:13 log.py[line:24] INFO info
Tue,28 Dec 2021 17:21:13 log.py[line:25] WARNING warning
Tue,28 Dec 2021 17:21:13 log.py[line:26] ERROR error
Tue,28 Dec 2021 17:21:13 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 17:21:34 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 17:21:34 log.py[line:24] INFO info
Tue,28 Dec 2021 17:21:34 log.py[line:25] WARNING warning
Tue,28 Dec 2021 17:21:34 log.py[line:26] ERROR error
Tue,28 Dec 2021 17:21:34 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 17:42:31 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 17:42:31 log.py[line:24] INFO info
Tue,28 Dec 2021 17:42:31 log.py[line:25] WARNING warning
Tue,28 Dec 2021 17:42:31 log.py[line:26] ERROR error
Tue,28 Dec 2021 17:42:31 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 17:45:55 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 17:45:55 log.py[line:24] INFO info
Tue,28 Dec 2021 17:45:55 log.py[line:25] WARNING warning
Tue,28 Dec 2021 17:45:55 log.py[line:26] ERROR error
Tue,28 Dec 2021 17:45:55 log.py[line:27] CRITICAL critical
Tue,28 Dec 2021 19:16:55 log.py[line:23] DEBUG debug
Tue,28 Dec 2021 19:16:55 log.py[line:24] INFO info
Tue,28 Dec 2021 19:16:55 log.py[line:25] WARNING warning
Tue,28 Dec 2021 19:16:55 log.py[line:26] ERROR error
Tue,28 Dec 2021 19:16:55 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 10:33:39 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 10:33:39 log.py[line:24] INFO info
Wed,29 Dec 2021 10:33:39 log.py[line:25] WARNING warning
Wed,29 Dec 2021 10:33:39 log.py[line:26] ERROR error
Wed,29 Dec 2021 10:33:39 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 15:14:18 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 15:14:18 log.py[line:24] INFO info
Wed,29 Dec 2021 15:14:18 log.py[line:25] WARNING warning
Wed,29 Dec 2021 15:14:18 log.py[line:26] ERROR error
Wed,29 Dec 2021 15:14:18 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 15:14:23 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 15:14:23 log.py[line:24] INFO info
Wed,29 Dec 2021 15:14:23 log.py[line:25] WARNING warning
Wed,29 Dec 2021 15:14:23 log.py[line:26] ERROR error
Wed,29 Dec 2021 15:14:23 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 15:35:47 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 15:35:47 log.py[line:24] INFO info
Wed,29 Dec 2021 15:35:47 log.py[line:25] WARNING warning
Wed,29 Dec 2021 15:35:47 log.py[line:26] ERROR error
Wed,29 Dec 2021 15:35:47 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 16:03:14 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 16:03:14 log.py[line:24] INFO info
Wed,29 Dec 2021 16:03:14 log.py[line:25] WARNING warning
Wed,29 Dec 2021 16:03:14 log.py[line:26] ERROR error
Wed,29 Dec 2021 16:03:14 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 16:53:32 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 16:53:32 log.py[line:24] INFO info
Wed,29 Dec 2021 16:53:32 log.py[line:25] WARNING warning
Wed,29 Dec 2021 16:53:32 log.py[line:26] ERROR error
Wed,29 Dec 2021 16:53:32 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 17:10:13 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 17:10:13 log.py[line:24] INFO info
Wed,29 Dec 2021 17:10:14 log.py[line:25] WARNING warning
Wed,29 Dec 2021 17:10:14 log.py[line:26] ERROR error
Wed,29 Dec 2021 17:10:14 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 17:10:20 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 17:10:20 log.py[line:24] INFO info
Wed,29 Dec 2021 17:10:20 log.py[line:25] WARNING warning
Wed,29 Dec 2021 17:10:20 log.py[line:26] ERROR error
Wed,29 Dec 2021 17:10:20 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 17:10:36 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 17:10:36 log.py[line:24] INFO info
Wed,29 Dec 2021 17:10:36 log.py[line:25] WARNING warning
Wed,29 Dec 2021 17:10:36 log.py[line:26] ERROR error
Wed,29 Dec 2021 17:10:36 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 17:12:58 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 17:12:58 log.py[line:24] INFO info
Wed,29 Dec 2021 17:12:58 log.py[line:25] WARNING warning
Wed,29 Dec 2021 17:12:58 log.py[line:26] ERROR error
Wed,29 Dec 2021 17:12:58 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 17:14:09 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 17:14:09 log.py[line:24] INFO info
Wed,29 Dec 2021 17:14:09 log.py[line:25] WARNING warning
Wed,29 Dec 2021 17:14:09 log.py[line:26] ERROR error
Wed,29 Dec 2021 17:14:09 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 19:07:05 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 19:07:05 log.py[line:24] INFO info
Wed,29 Dec 2021 19:07:05 log.py[line:25] WARNING warning
Wed,29 Dec 2021 19:07:05 log.py[line:26] ERROR error
Wed,29 Dec 2021 19:07:05 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 19:08:01 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 19:08:01 log.py[line:24] INFO info
Wed,29 Dec 2021 19:08:01 log.py[line:25] WARNING warning
Wed,29 Dec 2021 19:08:01 log.py[line:26] ERROR error
Wed,29 Dec 2021 19:08:01 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.address`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.address` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.automotive`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.automotive` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.bank`.
Wed,29 Dec 2021 19:08:01 factory.py[line:101] DEBUG Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.barcode`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.barcode` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.color`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.color` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.company`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.company` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.credit_card`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.credit_card` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.currency`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.currency` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.date_time`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.date_time` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:113] DEBUG Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.geo`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.geo` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.internet`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.internet` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:113] DEBUG Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.job`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.job` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.lorem`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.lorem` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.misc`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.misc` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.person`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.person` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.phone_number`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.phone_number` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:113] DEBUG Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
Wed,29 Dec 2021 19:08:01 factory.py[line:113] DEBUG Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
Wed,29 Dec 2021 19:08:01 factory.py[line:94] DEBUG Looking for locale `en_US` in provider `faker.providers.ssn`.
Wed,29 Dec 2021 19:08:01 factory.py[line:106] DEBUG Provider `faker.providers.ssn` has been localized to `en_US`.
Wed,29 Dec 2021 19:08:01 factory.py[line:113] DEBUG Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
Wed,29 Dec 2021 19:08:01 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:02 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "POST /api/ajax/user/login/captcha HTTP/1.1" 200 None
Wed,29 Dec 2021 19:08:02 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:02 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "POST /api/ajax/user/login/captcha HTTP/1.1" 302 None
Wed,29 Dec 2021 19:08:02 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:03 connectionpool.py[line:452] DEBUG http://www.t.ifboss.com:80 "GET / HTTP/1.1" 200 None
Wed,29 Dec 2021 19:08:03 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:03 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "POST /api/ajax/user/login/captcha HTTP/1.1" 302 None
Wed,29 Dec 2021 19:08:03 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:03 connectionpool.py[line:452] DEBUG http://www.t.ifboss.com:80 "GET / HTTP/1.1" 200 None
Wed,29 Dec 2021 19:08:03 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:04 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "POST /api/ajax/user/login/captcha HTTP/1.1" 302 None
Wed,29 Dec 2021 19:08:04 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:04 connectionpool.py[line:452] DEBUG http://www.t.ifboss.com:80 "GET / HTTP/1.1" 200 None
Wed,29 Dec 2021 19:08:04 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:04 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "POST /api/ajax/user/login/captcha HTTP/1.1" 302 None
Wed,29 Dec 2021 19:08:04 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:04 connectionpool.py[line:452] DEBUG http://www.t.ifboss.com:80 "GET / HTTP/1.1" 200 None
Wed,29 Dec 2021 19:08:04 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:05 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "POST /api/ajax/user/login/captcha HTTP/1.1" 302 None
Wed,29 Dec 2021 19:08:05 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:05 connectionpool.py[line:452] DEBUG http://www.t.ifboss.com:80 "GET / HTTP/1.1" 200 None
Wed,29 Dec 2021 19:08:05 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): static.www.t.ifboss.com:80
Wed,29 Dec 2021 19:08:05 connectionpool.py[line:452] DEBUG http://static.www.t.ifboss.com:80 "POST /api/ajax/user/login/captcha HTTP/1.1" 302 None
Wed,29 Dec 2021 19:08:05 connectionpool.py[line:227] DEBUG Starting new HTTP connection (1): www.t.ifboss.com:80
Wed,29 Dec 2021 19:12:39 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 19:12:39 log.py[line:24] INFO info
Wed,29 Dec 2021 19:12:39 log.py[line:25] WARNING warning
Wed,29 Dec 2021 19:12:39 log.py[line:26] ERROR error
Wed,29 Dec 2021 19:12:39 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 19:16:22 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 19:16:22 log.py[line:24] INFO info
Wed,29 Dec 2021 19:16:22 log.py[line:25] WARNING warning
Wed,29 Dec 2021 19:16:22 log.py[line:26] ERROR error
Wed,29 Dec 2021 19:16:22 log.py[line:27] CRITICAL critical
Wed,29 Dec 2021 19:16:30 log.py[line:23] DEBUG debug
Wed,29 Dec 2021 19:16:30 log.py[line:24] INFO info
Wed,29 Dec 2021 19:16:30 log.py[line:25] WARNING warning
Wed,29 Dec 2021 19:16:30 log.py[line:26] ERROR error
Wed,29 Dec 2021 19:16:30 log.py[line:27] CRITICAL critical
